language: node_js

node_js:
  - 8

script:
  - npm run build

before_install:
  - npm i -g npm@5.6.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
